(() => {
  const allowed=/^(?:pp_(?:ccst_)?(?:practice_v1|stats|favorites|heart_limit|ranked_run_(?:all|shuffle|adaptive|blitz))|pp_(?:theme|motion|sound|leaderboard_name|live_name))$/;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let user=null,cloud={revision:0,data:{}},sync=false,busy=false,chosen=false,timer,mode='login';
  const mount=document.getElementById('accountMount');if(!mount)return;
  mount.innerHTML='<button type="button" class="account-header" id="accountButton">Sign in</button>';
  const dialog=document.createElement('dialog');dialog.className='account-dialog';dialog.setAttribute('aria-labelledby','accountTitle');document.body.append(dialog);
  function collect(){const data={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(allowed.test(k)){try{data[k]=JSON.parse(localStorage.getItem(k));}catch{}}}return data;}
  async function api(body){const r=await fetch('/api/account',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json','X-Packet-Account':'1'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not connect.');return data;}
  function status(message){const p=dialog.querySelector('.account-status');if(p)p.textContent=message;}
  function render(){document.getElementById('accountButton').textContent=user?user.username:'Sign in';dialog.innerHTML='<form method="dialog"><button class="dialog-close" aria-label="Close account">×</button></form><span class="section-kicker">YOUR PROGRESS, WITH YOU</span><h2 id="accountTitle">'+(user?'Hi, '+esc(user.username)+'.':mode==='register'?'Make yourself at home.':mode==='recover'?'Recover your account.':'Welcome back.')+'</h2>'+(user?`<p class="account-note">Both decks, practice progress, paused ranked runs, favorites and preferences can be saved. Guest play is always available.</p><p>Cloud save: ${cloud.updatedAt?esc(new Date(cloud.updatedAt).toLocaleString()):'No progress saved yet'}</p><div class="account-actions"><button type="button" data-account="upload">Save this device to cloud</button><button type="button" data-account="download" ${cloud.revision?'':'disabled'}>Use cloud on this device</button></div><label><input type="checkbox" id="autoSync" ${sync?'checked':''} ${chosen?'':'disabled'}> Auto-save after choosing a save above</label><p class="account-note">Saving replaces the previous cloud copy. Loading replaces study progress on this device and reloads the page. A backup is kept on this device.</p><div class="account-actions"><button type="button" data-account="refresh">Refresh cloud status</button><button type="button" data-account="logout">Sign out</button></div>`:`<p class="account-note">Optional account. Save your study progress across devices.</p><form class="account-form"><label>Username<input name="username" autocomplete="username" pattern="[A-Za-z0-9_]{3,24}" minlength="3" maxlength="24" required></label>${mode==='recover'?'<label>Recovery key<input name="recoveryKey" autocomplete="off" required maxlength="100"></label>':''}<label>${mode==='recover'?'New password':'Password'}<input name="password" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="12" maxlength="128" required></label><small class="account-note">12+ characters. Try a memorable phrase. No email required.</small><button class="button button-primary" type="submit">${mode==='register'?'Create account':mode==='recover'?'Reset password':'Sign in'}</button></form><div class="account-actions"><button type="button" data-account="mode" data-mode="${mode==='register'?'login':'register'}">${mode==='register'?'Already have an account?':'Create an account'}</button><button type="button" data-account="mode" data-mode="recover">Forgot password?</button></div>`)+ '<p class="account-status" role="status"></p>';}
  async function refresh(){const data=await api();if(user&&user.id!==data.user?.id){sync=false;chosen=false;}user=data.user;cloud=data.cloud||{revision:0,data:{}};render();}
  async function save(){if(!user||busy)return;busy=true;try{const result=await api({action:'save',userId:user.id,revision:cloud.revision,data:collect()});cloud={...result,data:collect()};chosen=true;render();status('Progress saved. You can enable auto-save for this session.');}catch(e){sync=false;status(e.message);const check=dialog.querySelector('#autoSync');if(check)check.checked=false;document.getElementById('accountButton').textContent='Save paused';}finally{busy=false;}}
  window.packetAccountProgressChanged=k=>{if(!allowed.test(k)||!sync||!user)return;clearTimeout(timer);timer=setTimeout(save,6000);};
  document.getElementById('accountButton').onclick=async()=>{render();dialog.showModal();try{await refresh();}catch(e){status(e.message);}};
  dialog.addEventListener('submit',async e=>{if(!e.target.matches('.account-form'))return;e.preventDefault();if(busy)return;busy=true;const button=e.target.querySelector('button[type=submit]');button.disabled=true;status('Connecting…');try{const values=Object.fromEntries(new FormData(e.target));const data=await api({action:mode,...values});user=data.user;cloud=data.cloud;sync=false;chosen=false;render();if(data.recoveryKey){const box=document.createElement('div');box.innerHTML='<p><strong>Keep this recovery key somewhere safe.</strong> It replaces email recovery and is only shown now.</p><code class="recovery-code">'+esc(data.recoveryKey)+'</code>';dialog.querySelector('.account-status').before(box);}status('Choose which progress to use before enabling auto-save.');}catch(err){status(err.message);button.disabled=false;}finally{busy=false;}});
  dialog.addEventListener('change',e=>{if(e.target.id==='autoSync'){sync=e.target.checked;if(sync)status('Auto-save is on for this browser session. Choose Save this device or Use cloud first if the copies differ.');}});
  dialog.addEventListener('click',async e=>{const b=e.target.closest('[data-account]');if(!b||busy)return;const action=b.dataset.account;if(action==='mode'){mode=b.dataset.mode;render();return;}try{if(action==='refresh')await refresh();if(action==='upload'){if(!confirm('Replace your cloud progress with this device’s progress?'))return;await save();}if(action==='download'){if(!confirm('Replace this device’s study progress with the cloud copy? A local backup will be kept.'))return;const latest=await api();if(latest.user?.id!==user.id)throw new Error('The signed-in account changed. Refresh and try again.');const backup=collect();localStorage.setItem('pp_account_local_backup',JSON.stringify({at:Date.now(),data:backup}));Object.keys(backup).forEach(k=>localStorage.removeItem(k));for(const [k,v]of Object.entries(latest.cloud.data))if(allowed.test(k))localStorage.setItem(k,JSON.stringify(v));location.reload();}if(action==='logout'){sync=false;chosen=false;clearTimeout(timer);await api({action:'logout'});user=null;cloud={revision:0,data:{}};render();status('Signed out. Progress on this device is still here.');}}catch(err){status(err.message);}});
  refresh().catch(()=>{});
})();
